export const DecorationMetadata =
{
    rock: { groundRadius: 4, canopyRadius: 0 },
    cactus: { groundRadius: 1.5, canopyRadius: 0 },
    bush: { groundRadius: 2.5, canopyRadius: 0 },
    willow: { groundRadius: 0.5, canopyRadius: 5.6 },
    poplar: { groundRadius: 0.3, canopyRadius: 2.1 },
    oak: { groundRadius: 0.7, canopyRadius: 8.7 },
    elm: { groundRadius: 0.6, canopyRadius: 9.1 },
    umbrella: { groundRadius: 0.5, canopyRadius: 9.2 },
    open: { groundRadius: 0.2, canopyRadius: 6.3 },
    irregular: { groundRadius: 0.3, canopyRadius: 7.2 },
    vase: { groundRadius: 0.3, canopyRadius: 3.8 },
    elder: { groundRadius: 6, canopyRadius: 50.9 },
    birch: { groundRadius: 0.6, canopyRadius: 10.8 },
    palm: { groundRadius: 0.3, canopyRadius: 6.8 },
    daisy: { groundRadius: 2.3, canopyRadius: 0 },
    lily: { groundRadius: 2.8, canopyRadius: 0 },
    waterlily: { groundRadius: 2.7, canopyRadius: 0 },
    cycad: { groundRadius: 0.4, canopyRadius: 4.4 },
    treeFern: { groundRadius: 0.2, canopyRadius: 4.7 },
    mangrove: { groundRadius: 12.8, canopyRadius: 18.1 },
    beachChair: { groundRadius: 1.1, canopyRadius: 0 },
    beachUmbrella: { groundRadius: 0.1, canopyRadius: 0.8 },
};
