export enum EntityIds {
    // Animals
    ALLIGATOR = 'alligator',
    BRONTOSAURUS = 'brontosaurus',
    TREX = 'trex',
    BROWN_BEAR = 'brownBear',
    POLAR_BEAR = 'polarBear',
    HIPPO = 'hippo',
    MONKEY = 'monkey',
    MOOSE = 'moose',
    TRICERATOPS = 'triceratops',
    DOLPHIN = 'dolphin',
    NARWHAL = 'narwhal',
    DUCKLING = 'duckling',
    BUTTERFLY = 'butterfly',
    PTERODACTYL = 'pterodactyl',
    BLUEBIRD = 'bluebird',
    PARROT = 'parrot',
    EGRET = 'egret',
    DRAGONFLY = 'dragonfly',
    SNAKE = 'snake',
    TURTLE = 'turtle',

    // Obstacles & Others
    LOG = 'log',
    ROCK = 'rock',
    BUOY = 'buoy',
    BOTTLE = 'bottle',
    MANGROVE = 'mangrove',
    WATER_GRASS = 'water_grass',
    LILLY_PAD_PATCH = 'lilly_pad_patch',
    PIER = 'pier',
    ICEBERG = 'iceberg',
    PENGUIN_KAYAK = 'penguinKayak',
    SWAN = 'swan',
    UNICORN = 'unicorn',
    GINGERMAN = 'gingerman'
}
