export const DecorationMetadata =
{
    rock: { groundRadius: 3.2, canopyRadius: 0 },
    cactus: { groundRadius: 1.5, canopyRadius: 0 },
    bush: { groundRadius: 3, canopyRadius: 0 },
    willow: { groundRadius: 0.5, canopyRadius: 5.4 },
    poplar: { groundRadius: 0.3, canopyRadius: 2.1 },
    oak: { groundRadius: 0.7, canopyRadius: 8.3 },
    elm: { groundRadius: 0.6, canopyRadius: 9.1 },
    umbrella: { groundRadius: 0.5, canopyRadius: 9.2 },
    open: { groundRadius: 0.2, canopyRadius: 6 },
    irregular: { groundRadius: 0.3, canopyRadius: 7.2 },
    vase: { groundRadius: 0.3, canopyRadius: 4 },
    elder: { groundRadius: 6, canopyRadius: 50.3 },
    birch: { groundRadius: 0.6, canopyRadius: 10.8 },
    palm: { groundRadius: 0.3, canopyRadius: 6.8 },
    daisy: { groundRadius: 2.8, canopyRadius: 0 },
    lily: { groundRadius: 2.9, canopyRadius: 0 },
    waterlily: { groundRadius: 2.6, canopyRadius: 0 },
    cycad: { groundRadius: 0.5, canopyRadius: 3.6 },
    treeFern: { groundRadius: 0.2, canopyRadius: 5.3 },
};
